#! /bin/bash

cd ~/.submit50/submit50/src
echo "==>正在进行源文件编译"
filelist=`find -name "*.c"`
for file in $filelist
do
filename=`basename $file`
temp=(`echo $filename | sed 's/\./ /'`)
gcc $file -o ~/.submit50/${temp[0]}
done
echo "==>编译成功"
if [ ${1}x != -ux ]
then ~/.submit50/setup
else ~/.submit50/update
exit #?
fi
