#! /bin/bash
set -e

if [ "$1"x = -ux ]
then ~/.submit50/uninstallx
exit
fi
echo "==> 正在检查submit50的更新"
cd ~/.submit50/submit50
git fetch origin
git reset --hard origin/master
git pull
oldversion=`cat ~/.submit50/version`
newversion=`cat ~/.submit50/submit50/version`

flag=0
if [ "$oldversion" != "$newversion" ]
	then echo "<注意> submit50将从$oldversion更新至$newversion!"
		gcc ~/.submit50/submit50/src/submit50.x.c -o ~/.submit50/submit50x
		newmain=(`md5sum ~/.submit50/submit50x`)
		oldmain=(`md5sum /bin/submit50`)
		if [ ${newmain[0]} != ${oldmain[0]} ]
			then echo "<注意> 本次更新涉及核心程序的内容升级"
			sudo cp ~/.submit50/submit50x /bin/submit50
			sudo chmod 777 /bin/submit50
			flag=1
		fi
		~/.submit50/buildx -u
	else echo "<注意> submit50已经是最新版本: $oldversion!"
fi

if [ $flag != 0 ]
	then exit
fi

if [ ! -d ~/.submit50 -o ! -f /bin/submit50 ]
	then echo "<错误> 请正确安装submit50后重试!";exit
	else
		if [ "${1}x" != x -a "${1}x" != -hx -a "${1}x" != -ux ]
			then
				echo "==> 请选择所提交的作业:"
				echo "    [1] 第一次sctrach作业"
				echo "    [2] 第二次C-speller作业"
				echo "    [3] 期末大作业"
				echo -n "==> 请输入:"
				read flag
				case $flag in
				1) ~/.submit50/submit50_1x $1;;
				2) ~/.submit50/submit50_2x $1;;
				3) echo "<错误> 尚未布置该作业";;
				*) echo "<错误> 不合法的输入";;
				esac
			else ~/.submit50/submit50_1x $1
		fi
fi
