#! /bin/bash

echo "==>正在检查submit50的更新"
cd ~/.submit50/submit50
git pull origin master:master
oldversion=`cat ~/.submit50/version`
newversion=`cat ~/.submit50/submit50/verison`
if [ $oldversion != $newversion ]
then echo "<注意> submit50将从$oldversion更新至$newversion!"
~/.submit50/submit50/build -u
if [ #? != 0 ]
then echo "<注意> 本次更新涉及核心程序,请重新运行submit50"
exit
fi
else echo "<注意> submit50已经是最新版本: $oldversion!"
fi

if [ ! -d ~/.submit50 -o ! -f ~/.submit50/submit50x ]
then echo "<错误> 请正确安装submit50后重试!";exit
else ~/.submit50/submit50x \'$1\'
fi
